### ISSUE TITLE
Docs: undeclared variable

### ISSUE THREAD

**Issue by Hypnosphi** [motorcyclejs/collection#3]
Should be `content`, I suppose: https://github.com/motorcyclejs/collection/blame/master/README.md#L145

**Comment by axefrog** [comment]
Thanks! I literally only released this about 12 hours ago, so there will be some rough edges to clean up.

**Comment by axefrog** [comment]
I thought you found a typo, but on second look, it seems as though you're disagreeing with the example section name...

**Comment by Hypnosphi** [comment]
No, I meant the typo

**Comment by axefrog** [comment]
Right you are, my bad. Thanks for the report :)

**Comment by Hypnosphi** [comment]
And above, `const header = Header(sources)` it might be meant to be

**Comment by axefrog** [comment]
Yep fixed that too :+1:
